# -*- coding: utf-8 -*-
"""Aula de Programção(lista, for e .append).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hAzN07pVyecp-Wp7_tx66Vh9Kao2vMfh
"""

lista = ['Álan', 'João', 'Carlos', 'Yuri', 'Edson']
for pessoas in lista:
    print(pessoas)

for caracter in "Python":
    print(caracter)

for c in range(0,11,2):
    print(c)

numero = 10
while numero >=0:
 print(f'o numero é {numero}')
 numero = numero-1

lista = [2, 3, 4]
lista.append(5)
lista

lista = ['Álan', 'João','Carlos']
lista.append('Deyvisson')
lista

a = 0
b = 3
if a == 0:
    print(f'a recebeu {a}')
elif a == 3:
    print(f'a recebeu {b}')

n1 = 10 
n2 = 13
n3 
if n1 < n2:
    n3 = n1+n2
n3

nome = 'detergente'
print(nome[0:10])

a = 10
b = 3
a = b
c = a+b
b = 0
d = a+b
print(f' o numero da variavel é {d}')

lista = [5,4,2]
lista[1] = 10
lista = lista+[11,6,7]
print(lista)

x = 10
x+=5
x

z = 20
z-10
z